// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"mandacode.com/accounts/user/ent/schema"
	"mandacode.com/accounts/user/ent/sentemail"
	"mandacode.com/accounts/user/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sentemailFields := schema.SentEmail{}.Fields()
	_ = sentemailFields
	// sentemailDescEmail is the schema descriptor for email field.
	sentemailDescEmail := sentemailFields[2].Descriptor()
	// sentemail.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	sentemail.EmailValidator = sentemailDescEmail.Validators[0].(func(string) error)
	// sentemailDescSentAt is the schema descriptor for sent_at field.
	sentemailDescSentAt := sentemailFields[3].Descriptor()
	// sentemail.DefaultSentAt holds the default value on creation for the sent_at field.
	sentemail.DefaultSentAt = sentemailDescSentAt.Default.(func() time.Time)
	// sentemailDescID is the schema descriptor for id field.
	sentemailDescID := sentemailFields[0].Descriptor()
	// sentemail.DefaultID holds the default value on creation for the id field.
	sentemail.DefaultID = sentemailDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[1].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescIsBlocked is the schema descriptor for is_blocked field.
	userDescIsBlocked := userFields[2].Descriptor()
	// user.DefaultIsBlocked holds the default value on creation for the is_blocked field.
	user.DefaultIsBlocked = userDescIsBlocked.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescIsArchived is the schema descriptor for is_archived field.
	userDescIsArchived := userFields[6].Descriptor()
	// user.DefaultIsArchived holds the default value on creation for the is_archived field.
	user.DefaultIsArchived = userDescIsArchived.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
