// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"mandacode.com/accounts/user/ent/sentemail"
	"mandacode.com/accounts/user/ent/user"
)

// SentEmailCreate is the builder for creating a SentEmail entity.
type SentEmailCreate struct {
	config
	mutation *SentEmailMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (sec *SentEmailCreate) SetUserID(u uuid.UUID) *SentEmailCreate {
	sec.mutation.SetUserID(u)
	return sec
}

// SetEmail sets the "email" field.
func (sec *SentEmailCreate) SetEmail(s string) *SentEmailCreate {
	sec.mutation.SetEmail(s)
	return sec
}

// SetSentAt sets the "sent_at" field.
func (sec *SentEmailCreate) SetSentAt(t time.Time) *SentEmailCreate {
	sec.mutation.SetSentAt(t)
	return sec
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (sec *SentEmailCreate) SetNillableSentAt(t *time.Time) *SentEmailCreate {
	if t != nil {
		sec.SetSentAt(*t)
	}
	return sec
}

// SetID sets the "id" field.
func (sec *SentEmailCreate) SetID(u uuid.UUID) *SentEmailCreate {
	sec.mutation.SetID(u)
	return sec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sec *SentEmailCreate) SetNillableID(u *uuid.UUID) *SentEmailCreate {
	if u != nil {
		sec.SetID(*u)
	}
	return sec
}

// SetUser sets the "user" edge to the User entity.
func (sec *SentEmailCreate) SetUser(u *User) *SentEmailCreate {
	return sec.SetUserID(u.ID)
}

// Mutation returns the SentEmailMutation object of the builder.
func (sec *SentEmailCreate) Mutation() *SentEmailMutation {
	return sec.mutation
}

// Save creates the SentEmail in the database.
func (sec *SentEmailCreate) Save(ctx context.Context) (*SentEmail, error) {
	sec.defaults()
	return withHooks(ctx, sec.sqlSave, sec.mutation, sec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SentEmailCreate) SaveX(ctx context.Context) *SentEmail {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SentEmailCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SentEmailCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SentEmailCreate) defaults() {
	if _, ok := sec.mutation.SentAt(); !ok {
		v := sentemail.DefaultSentAt()
		sec.mutation.SetSentAt(v)
	}
	if _, ok := sec.mutation.ID(); !ok {
		v := sentemail.DefaultID()
		sec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SentEmailCreate) check() error {
	if _, ok := sec.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SentEmail.user_id"`)}
	}
	if _, ok := sec.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "SentEmail.email"`)}
	}
	if v, ok := sec.mutation.Email(); ok {
		if err := sentemail.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SentEmail.email": %w`, err)}
		}
	}
	if _, ok := sec.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "SentEmail.sent_at"`)}
	}
	if len(sec.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SentEmail.user"`)}
	}
	return nil
}

func (sec *SentEmailCreate) sqlSave(ctx context.Context) (*SentEmail, error) {
	if err := sec.check(); err != nil {
		return nil, err
	}
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	sec.mutation.id = &_node.ID
	sec.mutation.done = true
	return _node, nil
}

func (sec *SentEmailCreate) createSpec() (*SentEmail, *sqlgraph.CreateSpec) {
	var (
		_node = &SentEmail{config: sec.config}
		_spec = sqlgraph.NewCreateSpec(sentemail.Table, sqlgraph.NewFieldSpec(sentemail.FieldID, field.TypeUUID))
	)
	if id, ok := sec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := sec.mutation.Email(); ok {
		_spec.SetField(sentemail.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := sec.mutation.SentAt(); ok {
		_spec.SetField(sentemail.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if nodes := sec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sentemail.UserTable,
			Columns: []string{sentemail.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SentEmailCreateBulk is the builder for creating many SentEmail entities in bulk.
type SentEmailCreateBulk struct {
	config
	err      error
	builders []*SentEmailCreate
}

// Save creates the SentEmail entities in the database.
func (secb *SentEmailCreateBulk) Save(ctx context.Context) ([]*SentEmail, error) {
	if secb.err != nil {
		return nil, secb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SentEmail, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SentEmailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SentEmailCreateBulk) SaveX(ctx context.Context) []*SentEmail {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SentEmailCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SentEmailCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}
