name: Build and Push on Tag

on:
  push:
    tags:
      - "v*"

env:
  DOCKER_FILES: |
    auth/docker/auth.Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          IFS=$'\n'  # ensure multiline parsing works
          VERSION="${GITHUB_REF#refs/tags/}"

          for DOCKER_FILE in $DOCKER_FILES; do
            BASENAME=$(basename "$DOCKER_FILE")      
            NAME=${BASENAME%%.*}                        
            CONTEXT="$(dirname "$DOCKER_FILE")" 
            IMAGE_NAME="${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${NAME}:${VERSION}"

            echo "🚀 Building and pushing image: $IMAGE_NAME"
            docker build -f "$DOCKER_FILE" -t "$IMAGE_NAME" "$CONTEXT"
            docker push "$IMAGE_NAME"
          done
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}
          DOCKER_FILES: ${{ env.DOCKER_FILES }}

      - name: Logout from Docker Registry
        run: docker logout ${{ vars.DOCKER_REGISTRY }}
        if: always()

      - name: Notify Success
        if: success()
        run: echo "✅ Docker images built and pushed successfully."

      - name: Notify Failure
        if: failure()
        run: echo "❌ Failed to build and push Docker images."
        continue-on-error: true
